# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[46,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/LPPronouns/issues"

[[mods]]
modId = "lppronouns"
version = "${file.jarVersion}"
displayName = "LPPronouns"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/LPPronouns/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/LPPronouns"
logoFile="LPPronouns.png"
credits="Special thanks to Luck and the LuckPerms maintainers for making a great permissions API."
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
A simple, cross API plugin that allows players to set their pronouns.
'''

# Forge Dependency
[[dependencies.lppronouns]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.lppronouns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1)"
ordering = "NONE"
side = "BOTH"

# LuckPerms dependency
[[dependencies.lppronouns]]
modId = "luckperms"
mandatory = true
versionRange = "[5.3.0,)"
ordering = "AFTER"
side = "SERVER"

