modLoader = "javafml"
loaderVersion = "[41,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/LPPronouns/issues"

[[mods]]
modId = "lppronouns"
version = "${file.jarVersion}"
displayName = "LPPronouns"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/p0t4t0sandwich/LPPronouns"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="LPPronouns.png" #optional
credits="Special thanks to Luck and the LuckPerms maintainers for making a great permissions API."
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
A simple, cross API plugin that allows players to set their pronouns.
'''

# Forge Dependency
[[dependencies.lppronouns]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.lppronouns]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"

# LuckPerms dependency
[[dependencies.lppronouns]]
modId = "luckperms"
mandatory = true
versionRange = "[5.3.0,)"
ordering = "AFTER"
side = "SERVER"

